import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";

export default function Layout({ children, title }) {
  return (
    <div>
      <Head>
        <title>Mis heros</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />

        <link
          href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Lobster&family=Luckiest+Guy&family=Outfit:wght@100;200;300;400;500;600;700;800;900&family=Righteous&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Header />
      {children}
      {title === "Home" ? <Footer /> : ""}
    </div>
  );
}
